from typing import Callable


class TSignals:
    def __init__(self): ...
    def connect(self, key: str, callback: Callable): ...
    def disconnect(self, key: str, func_id: int): ...
    def clear(self): ...
    def clear_key(self, key: str): ...
    def register_keys(self, keys: list[str]): ...
    def add_omit(self, key: str): ...
    def remove_omit(self, key: str): ...
    def get_keys(self): ...
    def get_omits(self): ...
    def get_listener(self, key: str): ...
    def has_key(self, key: str): ...
    def is_omitted(self, key: str): ...
    def listener_count(self, key: str): ...
    def call(self, key: str, *args): ...
    def __call__(self, key: str, *args): ...
    
